### ISSUE TITLE
 'TException' with message 'TSocket: Could not connect to localhost:10000

### ISSUE THREAD

**Issue by aditya-** [garamon/php-thrift-hive-client#1]
Dear @garamon 

I've installed hadoop, hive and apache thrift in my system  . I cloned this repository and placed at my apache  folder (/var/www) when i open this file .. its showing me blank page . When i run this from command line its showing me following error.

```
root@aaryan-pc:/usr/share/nginx/www/php-thrift-hive-client# php sample.php 
PHP Fatal error:  Uncaught exception 'TException' with message 'TSocket: Could not connect to localhost:10000 (Connection refused [111])' in /usr/share/nginx/www/php-thrift-hive-client/lib/transport/TSocket.php:191
Stack trace:
#0 /usr/share/nginx/www/php-thrift-hive-client/ThriftHiveClientEx.php(35): TSocket->open()
#1 /usr/share/nginx/www/php-thrift-hive-client/sample.php(13): ThriftHiveClientEx->open()
#2 {main}
  thrown in /usr/share/nginx/www/php-thrift-hive-client/lib/transport/TSocket.php on line 191
```

My Environment :

OS : Ubuntu 12.04 LTS Precise 32-bit
server: Apache
Installed : Hadoop , Hive , Apache Thrift 

Please help me to fix this issue

**Comment by aditya-** [comment]
@garamon  can you please look at this issue
